# Generated by Django 5.0.14 on 2026-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('project_url', models.URLField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
