# Generated by Django 5.0.14 on 2026-09-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='title_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
