# Generated by Django 5.0.14 on 2026-09-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seed_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_id', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('organization_id', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('description_id', models.TextField(blank=True, default='')),
                ('category', models.CharField(max_length=100)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_portfolio_experience',
            },
        ),
    ]
