# Generated by Django 5.0.14 on 2026-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_seed_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_id', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('result_id', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'title'),
            },
        ),
    ]
