# Generated by Django 5.0.14 on 2026-09-28 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_experience_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
